### PR TITLE
Performance and optimizations.

### PR DESCRIPTION
**Pull request by germanfr**
* Simplify project setup by removing grunt and node stuff, which is not truly necessary.
* Performance improvements when loading options at startup.
* Added the ability to have custom date formats per language.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Would you mind pulling from upstream to fix your conflicts?

**Comment by germanfr** [comment]
Of course. I'll do when I get back home.

**Comment by ErikBoesen** [comment]
Thank you!

**Comment by germanfr** [comment]
Github has a new feature to resolve conflicts right here. It was easier than creating a new branch form upstream. There should not be conflicts now.

**Pull request merged**
