### PR TITLE
Reorganized scripts to load at the bottom of the html bodies

### PR DESCRIPTION
**Pull request by atf1999**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
@germanfr, thoughts on this? I think you told me this was a bad idea.

**Comment by ErikBoesen** [comment]
(Tom, this is normally a good idea, you're right. But I recall Germán telling me there was some reason that it wasn't the best option in this case.)

**Comment by germanfr** [comment]
It does not make any difference. But be aware that everything is executed on DOM content loaded event, which I can't say it will be fired always if you write it after. I think yes, but can't say.

**Comment by germanfr** [comment]
Also, read the _how to contribute_ section in the readme. I know it's kind of so much work to do for such a tiny project, but I think it's worth the time every millisecond in a page that is used that often.

**Comment by ErikBoesen** [comment]
_Needs more rigor_

**Comment by germanfr** [comment]
Well, someone with lots of reputation in StackOverflow said [it will work](http://stackoverflow.com/questions/39945136/can-domcontentloaded-event-not-be-fired-in-any-circumstance). If you still interested in this, I encourage you to add the minified files. [Here's how](https://github.com/ErikBoesen/BWNT#contributing).

**Comment by atf1999** [comment]
@germanfr will do. Ive been at a college visit all day so I haven't had time

**Comment by germanfr** [comment]
Hey guys. I think this went over-complicated for such a tiny program and I removed all that complicated stuff [here](https://github.com/germanfr/BWNT/commit/6cdf71432dce84829012df1da87792ce013748b9) and added your change, so this can be closed.

And now I read my previous comments, I don't even know why did I ask for minified files if there's no diff for them in this commit. Sorry guys :sweat_smile:

**Comment by ErikBoesen** [comment]
@germanfr Yes, that would be nice, thank you.

**Pull request closed without merging**
